# Generated by Django 5.1.4 on 2024-12-26 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
