# Generated by Django 5.1.4 on 2024-12-26 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManage', '0004_task_assignee_task_creator_task_reviewer_task_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManage.team'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
