# Generated by Django 5.1.4 on 2024-12-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManage', '0006_remove_user_team_membership_team_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
