# Generated by Django 5.1.4 on 2024-12-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManage', '0012_rename_membership_teammembers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
    ]
