# Generated by Django 5.1.4 on 2024-12-31 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManage', '0017_rename_users_teammembers_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammembers',
            old_name='role',
            new_name='team_role',
        ),
    ]
