# Generated by Django 5.1.4 on 2024-12-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManage', '0018_rename_role_teammembers_team_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammembers',
            old_name='username',
            new_name='user',
        ),
    ]
