# Generated by Django 5.1.4 on 2024-12-31 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManage', '0019_rename_username_teammembers_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammembers',
            old_name='user',
            new_name='username',
        ),
    ]
